[package]
name = "closet"
version = "0.1.0"
edition = "2018"
authors = ["Pikkel/tty3 <sopport@femboycock.club>"]

[dependencies]
pretty_env_logger = "0.4.0"
tokio = { version = "1.14.0", features = ["full"] }
warp = "0.3.2"

